print('Date: 09/03/2026')
print(' ')
print('   Im feeling thrilled about what Im learning.')
print('   I want to accomplish to understand code and possible fix bugs.')
print('   Im proud of you')
print('   😎')